[package]
name = "akhc"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
akhamoth = { path = "../akhamoth" }
clap = { version = "4.5.20", features = ["derive"] }
